# Generated by Django 4.0.4 on 2022-05-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relic',
            name='builds',
        ),
        migrations.RemoveField(
            model_name='statincreases',
            name='relic',
        ),
        migrations.AddField(
            model_name='build',
            name='relics',
            field=models.ManyToManyField(to='builder.relic'),
        ),
        migrations.AddField(
            model_name='relic',
            name='stat_increases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='builder.statincreases'),
        ),
    ]
