# Generated by Django 4.0.4 on 2022-05-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_remove_relic_builds_remove_statincreases_relic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relic',
            name='stat_increases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='builder.statincreases'),
        ),
    ]
