# Generated by Django 4.0.4 on 2022-05-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_relic_stat_increases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relic',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='statincreases',
            name='move_speed',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
