# Generated by Django 4.0.4 on 2022-05-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_relic_options_statincreases_move_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='relics',
            field=models.ManyToManyField(blank=True, to='builder.relic'),
        ),
    ]
